"""empty message

Revision ID: 137283d59f92
Revises: 8ff4e626736b
Create Date: 2024-10-01 12:39:12.908457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "137283d59f92"
down_revision: Union[str, None] = "8ff4e626736b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "section", sa.Column("position", sa.Integer(), nullable=False)
    )
    op.add_column(
        "subsection", sa.Column("position", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subsection", "position")
    op.drop_column("section", "position")
    # ### end Alembic commands ###
