"""empty message

Revision ID: 657bd3af8ddc
Revises: 6950e5cdb261
Create Date: 2024-09-18 18:37:18.928155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "657bd3af8ddc"
down_revision: Union[str, None] = "6950e5cdb261"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_type",
        sa.Column(
            "id", sa.BigInteger(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task",
        sa.Column(
            "id", sa.BigInteger(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("video", sa.String(), nullable=False),
        sa.Column("todo", sa.Boolean(), nullable=False),
        sa.Column("scores", sa.Integer(), nullable=False),
        sa.Column("task_type_id", sa.BigInteger(), nullable=False),
        sa.Column("subsection_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subsection_id"], ["subsection.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["task_type_id"], ["task_type.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submission",
        sa.Column(
            "submission_id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("submission_date", sa.DateTime(), nullable=False),
        sa.Column("submission_code", sa.Text(), nullable=False),
        sa.Column("submission_answer", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_account.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("submission_id"),
    )
    op.create_table(
        "task_test",
        sa.Column(
            "id", sa.BigInteger(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("expected_output", sa.Text(), nullable=False),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("answer_question_id_fkey", "answer", type_="foreignkey")
    op.drop_table("question")
    op.drop_table("content_section")
    op.add_column(
        "answer", sa.Column("task_id", sa.BigInteger(), nullable=False)
    )
    op.create_foreign_key(
        None, "answer", "task", ["task_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("answer", "question_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answer",
        sa.Column(
            "question_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "answer", type_="foreignkey")
    op.create_foreign_key(
        "answer_question_id_fkey",
        "answer",
        "question",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("answer", "task_id")
    op.create_table(
        "question",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "content_section_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_section_id"],
            ["content_section.id"],
            name="question_content_section_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="question_pkey"),
    )
    op.create_table(
        "content_section",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("video", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "subsection_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["subsection_id"],
            ["subsection.id"],
            name="content_section_subsection_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="content_section_pkey"),
    )
    op.drop_table("task_test")
    op.drop_table("submission")
    op.drop_table("task")
    op.drop_table("task_type")
    # ### end Alembic commands ###
