"""empty message

Revision ID: 8ff4e626736b
Revises: 690e6339641a
Create Date: 2024-09-30 21:13:33.310727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ff4e626736b"
down_revision: Union[str, None] = "690e6339641a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("video_path", sa.String(), nullable=True))
    op.alter_column("task", "text", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("task", "video")
    op.create_unique_constraint(None, "task_type", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task_type", type_="unique")
    op.add_column(
        "task",
        sa.Column("video", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column("task", "text", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("task", "video_path")
    # ### end Alembic commands ###
