"""empty message

Revision ID: c7a8b18b5aab
Revises: 137283d59f92
Create Date: 2024-10-10 19:42:47.059248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7a8b18b5aab"
down_revision: Union[str, None] = "137283d59f92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_test", sa.Column("test_file", sa.Text(), nullable=False))
    op.drop_column("task_test", "expected_output")
    op.drop_column("task_test", "input")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_test",
        sa.Column("input", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "task_test",
        sa.Column("expected_output", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("task_test", "test_file")
    # ### end Alembic commands ###
