"""empty message

Revision ID: ea98b1d7feac
Revises: c7a8b18b5aab
Create Date: 2024-10-11 18:13:40.724537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea98b1d7feac"
down_revision: Union[str, None] = "c7a8b18b5aab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission", sa.Column("todo", sa.Boolean(), nullable=False)
    )
    op.drop_column("task", "todo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("todo", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("submission", "todo")
    # ### end Alembic commands ###
