"""empty message

Revision ID: f1d74162b600
Revises: 277b242c9bbf
Create Date: 2024-08-24 18:31:18.775746

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1d74162b600"
down_revision: Union[str, None] = "277b242c9bbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course", sa.Column("title", sa.String(length=50), nullable=False)
    )
    op.add_column("course", sa.Column("describe", sa.Text(), nullable=True))
    op.drop_column("course", "name")
    op.drop_column("course", "text")
    op.add_column("section", sa.Column("describe", sa.Text(), nullable=True))
    op.drop_column("section", "text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "section",
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("section", "describe")
    op.add_column(
        "course",
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "course",
        sa.Column(
            "name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("course", "describe")
    op.drop_column("course", "title")
    # ### end Alembic commands ###
